spring:
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8500
  servlet:
    context-path: /

openai-service:
  gpt-model: gpt-3.5-turbo
  http-client:
    read-timeout: 30000
    connect-timeout: 30000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions

logging:
  level:
    com.github.wenqiglantz.service.openaiclient: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
